### ISSUE TITLE
Rename reconstruct_.json for each tile

### ISSUE THREAD

**Issue by Mboga** [Yarroudh/Optim3D#4]
Thanks for the tool. 

I am wondering in line 453 of reconstruct.json, if you should rename the reconstruct_.json for each of the new tile. This would happen after line 499 in main.py as data['nodes']['NestedFlowchart']['parameters'] = 'reconstruct{}_'.format(i) ?

Thank you

**Comment by Yarroudh** [comment]
Apparently, when changing the filepath to reconstruct{i}_.json, the reconstruction fails completely as it cannot point to the right file. You can find attached to this email the logs file.

These are the logs of the reconstruct file after adding:
`data['nodes']['NestedFlowchart']['parameters'] = 'reconstruct{}_'.format(i)`

[logs.txt](https://github.com/Yarroudh/Optim3D/files/11233972/logs.txt)

**Comment by Yarroudh** [comment]
First attempt to solve this problem: generating GPKG tiles instead fo Shapefile as the geometry type could be the reason for this error
Results: the error persists even with Polygon geometries.

**Comment by Yarroudh** [comment]
@Mboga can you try with this on line 499 instead of what you proposed:

` data['nodes']['NestedFlowchart']['parameters']['filepath'] = '{}/flowcharts/reconstruct{}_.json'.format(output, i)`

**Comment by Mboga** [comment]
Thanks @Yarroudh, this solves the error in the log.txt  but only lod0 reconstruction takes place when I use the exact workflow. I will recheck to ensure that all is correct in the new reconstruct.json  and reconstruct_.json files

**Comment by Mboga** [comment]
@Yarroudh, re-checked to ensure all paths are correct- and subsequently achieved successful lod22 reconstruction :)

**Comment by Yarroudh** [comment]
Great. Thanks for your feedback.
